using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class BasicDialog : MonoBehaviour
{

    public Button acceptButton;
    public Button declineButton;
    public Text titleText;
    public Text messageText;
    // Start is called before the first frame update
    void Start()
    {
        acceptButton.onClick.AddListener(acceptAction);
        declineButton.onClick.AddListener(declineAction);
    }

    public BasicDialog setTitleText(string title){
        titleText.text = title;
        return this;
    }

    public BasicDialog setMessageText(string message) {
        messageText.text = message;
        return this;
    }

    public void setAcceptButtonText(string buttonText) {
        acceptButton.GetComponent<Text>().text = buttonText;
    }

    public void setDeclineButtonText(string buttonText) {
        declineButton.GetComponent<Text>().text = buttonText;
    }

    void acceptAction() {
        
    }

    void declineAction() {

    }
}
