using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class AnswerTimeSlider : MonoBehaviour
{
    public string permanentText;
    public float startValue;

    private Text text;
    private string textAfterValue;
    // Start is called before the first frame update
    void Start()
    {
        text = GetComponent<Text>();
        textAfterValue = LocalizationManager.Instance.GetText(permanentText);
        textUpdate(startValue);
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    
    public void textUpdate(float value) {
        text.text = Math.Round(value) + " " + textAfterValue;
    }
}
