using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class InviteSearchResult : MonoBehaviour
{
    public Text userNameText;
    public Toggle shouldInvite;

    private int id;

    internal void SetName(string name) {
        userNameText.text = name;
    }

    public bool ShouldInvite() {
        return shouldInvite.isOn;
    }

    internal void SetId(int id) {
        this.id = id;
    }

    internal void SetId(string id) {
        Int32.TryParse(id, out int result);
        this.id = result;
    }

    internal string GetName() {
        return userNameText.text;
    }

    internal int GetId() {
        return id;
    }
}
