using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class invitePanelController : MonoBehaviour {
    public Button inviteButton;
    public GameObject InvitePanel;
    [SerializeField] Text invitedPlayersText;
    // Start is called before the first frame update
    void Start() {
        inviteButton.onClick.AddListener(OpenInvitePlayersDialog);
        invitedPlayersText.text = LocalizationManager.Instance.GetText("INVITED_PLAYERS_TEXT_START");
    }

    // Update is called once per frame
    void Update() {

    }

    public void updateText(int count) {
        invitedPlayersText.text = count + " " + LocalizationManager.Instance.GetText("INVITED_PLAYERS_TEXT");
    }

    void OpenInvitePlayersDialog() {
        InvitePanel.SetActive(true);
    }
}
