using System.Collections;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

public class NewQuestion : QuestionCard {
    // Start is called before the first frame update
    public Vector3 originalPos;
    public Quaternion originalRot;

    public Text CategoryText;

    void Start()
    {
        // Get question from server
        originalPos = this.transform.position;
        originalRot = this.transform.rotation;
    }

    private static NewQuestion instance;
    public static NewQuestion Instance() {
        if (!instance) {
            instance = FindObjectOfType(typeof(NewQuestion)) as NewQuestion;
            if (!instance) {
                Debug.Log("There need to be at least one active GenericDialog on the screen");
            }
        }
        return instance;
    }
}
