using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class StatsLine : MonoBehaviour
{

    public Text statName;
    public Text statValue;

    public void SetStatName(string value) {
        statName.text = value;
    }

    public void SetStatValue(string value) {
        statValue.text = value;
    }

    public string GetValue() {
        return statValue.text;
    }
    
    public void MakeBold() {
        statName.fontStyle = FontStyle.Bold;
        statValue.fontStyle = FontStyle.Bold;
    }

    public void UnBold() {
        statName.fontStyle = FontStyle.Normal;
        statValue.fontStyle = FontStyle.Normal;
    }
}
