using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class PlayerSetting : MonoBehaviour
{
    public Text nameText;
    public InputField nameInput;

    private LocalizationManager LANG = LocalizationManager.Instance;

    internal void SetPlayerText(int v) {
        string text = LANG.GetText("PLAYER_SETTING_TEXT");
        text = String.Format(text, v);
        nameText.text = text; 
    }

    internal void SetPlayerName(int v) {
        string text = LANG.GetText("PLAYER_TEXT") + " " + v.ToString();
        nameInput.text = text;
    }
}
