using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class PrivacyPolicy : MonoBehaviour
{
    Button pp;
    private string privacyPolicyLink = "http://nordh.xyz/narKampen/PrivacyPolicy/privacy_policy.html";

    // Start is called before the first frame update
    void Start()
    {
        pp = this.GetComponent<Button>();
        pp.onClick.AddListener(OpenWebpage);
    }

    private void OpenWebpage() {
        Application.OpenURL(privacyPolicyLink);
    }
}
